package exception;

public class Demo {

	// try, catch, finally, throw , throws
	public static void main(String[] args) {
		int a = 5;
		int b = 0;
		int c = 0;
		
		System.out.println("Going to divide...");
		
	}

}
